# Exercise: Describing Data

Answer the following questions about `exercise_data.csv`. Include your final code below. When you are done, click on `Run` > `Restart Kernel and Run All Cells...` and verify the output.
- Q: How many rows (a.k.a. observations) are in the dataset?
- A: 1000
- Q: How many columns (a.k.a. variables) are in the dataset?
- A: 10
- Q: What is the value of `points` in the first row?
- A: 42.0
- Q: Sort the dataset by `score`. What is the value of `points` in the first row?
- A: 80
- Q: Which variable has the highest average value?
- A: Score (572.18)
- Q: Which two categorical variables have the most unique values?
- A: Country and region both have 4 unique  values
- Q: What is the most frequent value of `country`?
- A: Iran
- Q: How often does "USA" appear in `country`?
- A: 242 times
- Q: How often does "female" occur in `gender`?
- A: 304
- Q: How often does "democratic" occur in `affiliation`?
- A: 343
- Q: How often does "south" occur in `region`?
- A: 246
- Q: What is the count of females who are democratic? (Hint: Group by `affiliation`)
- A: 100
- Q: What is the average of `tip` for females? (Hint: Group by `gender`)
- A:  5.298881
- Q: What is the median of `distance` for republicans? (Hint: Group by `affiliation`)
- A: 50.0

In [3]:
# Importing pandas as "pd"
import pandas as pd

In [4]:
# Loading DataFrame As "ED"
ED= pd.read_csv('ED.csv')

In [5]:
ED

,points,score,age,tip,country,distance,gender,temperature,affiliation,region
0,42.0,558.0,24.0,NaN,England,53.0,female,88.0,democratic,east
1,91.0,415.0,23.0,5.29,Wales,95.0,male,50.0,republican,south
2,73.0,475.0,22.0,6.19,Iran,NaN,female,68.0,independent,east
3,25.0,621.0,26.0,1.62,Iran,35.0,NaN,65.0,democratic,west
4,85.0,519.0,26.0,2.34,England,26.0,other,54.0,republican,west
...,...,...,...,...,...,...,...,...,...,...
995,99.0,623.0,18.0,4.27,Wales,69.0,male,75.0,independent,south
996,19.0,406.0,27.0,2.83,Wales,86.0,female,43.0,democratic,west
997,48.0,696.0,NaN,6.35,Wales,72.0,other,82.0,independent,west
998,48.0,440.0,19.0,8.85,England,32.0,male,41.0,republican,east
999,97.0,306.0,24.0,6.61,Iran,66.0,female,74.0,independent,east

In [6]:
# Loading basic Info
ED.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   points       989 non-null    float64
 1   score        980 non-null    float64
 2   age          919 non-null    float64
 3   tip          955 non-null    float64
 4   country      975 non-null    object
 5   distance     957 non-null    float64
 6   gender       960 non-null    object
 7   temperature  965 non-null    float64
 8   affiliation  977 non-null    object
 9   region       987 non-null    object
dtypes: float64(6), object(4)
memory usage: 78.3+ KB

In [7]:
# sorting values by "score"
ED.sort_values('score')

,points,score,age,tip,country,distance,gender,temperature,affiliation,region
147,80.0,299.0,24.0,4.40,Wales,16.0,other,64.0,republican,south
786,69.0,300.0,18.0,1.82,England,75.0,other,47.0,independent,south
529,27.0,301.0,23.0,1.42,USA,NaN,other,58.0,republican,west
393,58.0,301.0,27.0,9.98,England,99.0,female,84.0,republican,north
268,57.0,301.0,19.0,5.20,England,87.0,other,68.0,democratic,south
...,...,...,...,...,...,...,...,...,...,...
650,46.0,NaN,24.0,1.16,Wales,12.0,other,49.0,democratic,east
854,27.0,NaN,22.0,4.42,England,26.0,male,88.0,republican,east
878,35.0,NaN,22.0,6.97,Iran,23.0,male,NaN,republican,east
963,61.0,NaN,24.0,6.42,USA,61.0,other,59.0,republican,west
972,0.0,NaN,22.0,NaN,Iran,44.0,male,62.0,independent,east

In [8]:
# transposed data to see Which variable has the highest average value
ED.describe().T

,count,mean,std,min,25%,50%,75%,max
points,989.0,49.943377,28.609595,0.0,26.000,52.00,73.00,99.00
score,980.0,572.189796,158.021981,299.0,429.750,572.00,706.00,849.00
age,919.0,22.608270,2.824762,18.0,20.000,23.00,25.00,27.00
tip,955.0,5.433393,2.631982,1.0,3.175,5.45,7.76,9.99
distance,957.0,49.075235,28.794986,1.0,24.000,49.00,74.00,99.00
temperature,965.0,59.453886,17.311198,30.0,45.000,59.00,75.00,89.00

In [9]:
# Seeing unique values for categorial variables

In [10]:
ED['gender'].nunique()

3

In [11]:
ED['affiliation'].nunique()

3

In [12]:
ED['region'].nunique()

4

In [13]:
ED['country'].nunique()

4

In [14]:
# using value count function too see which coountry has the highest frequency
ED['country'].value_counts()

country
Iran       258
USA        242
England    240
Wales      235
Name: count, dtype: int64

In [15]:
# using value count function too see how many times females occur in 'gender'
ED['gender'].value_counts()

gender
other     335
male      321
female    304
Name: count, dtype: int64

In [16]:
#  using value count function too see How often does "democratic" occur in `affiliation`
ED['affiliation'].value_counts()

affiliation
democratic     343
republican     326
independent    308
Name: count, dtype: int64

In [17]:
#  using value count function too see How often does "south" occur in `region`
ED['region'].value_counts()

region
east     273
south    246
west     242
north    226
Name: count, dtype: int64

In [18]:
# using "groupby functions to see how mant times females occur in'democratic'"
ED.groupby('affiliation')['gender'].value_counts()

affiliation  gender
democratic   male      119
             other     110
             female    100
independent  other     105
             male      103
             female     86
republican   female    112
             other     111
             male       91
Name: count, dtype: int64

In [19]:
# using 'groupby' to see average tips by females
ED.groupby('gender')['tip'].mean()

gender
female    5.298881
male      5.583495
other     5.448063
Name: tip, dtype: float64

In [20]:
# using 'groupby' the median of `distance` for republicans
ED.groupby('affiliation')['distance'].median()

affiliation
democratic     47.0
independent    50.0
republican     50.0
Name: distance, dtype: float64