# Lab Project 3: Supermarket Sales

<br>**Context**</br>
The growth of supermarkets in most populated cities is increasing and market competition is also high. The dataset is one of the historical sales of supermarket company which has recorded in 3 different branches for 3 months data. Predictive data analytics methods are easy to apply to this dataset.

Supermarket sales are historical records of sales data in 3 different supermarkets. Please load `supermarket_sales.csv`, which contains data about almost 1000 invoice data from the Supermarket Store. Specifically, the file includes the following variables:
<br>Source: Kaggle

- `Invoice id`: Computer-generated sales slip invoice identification
- `Branch`: Branch of supercenter (3 branches are available identified by A, BC >
- `City`: Location of superstore
- `Customer type`: Type of customers, recorded by Members for customers using member cards and Normal for those without member cards.
- `Gender`: Gender type of customer
- `Product line`: General item categorization groups - Electronic accessories, Fashion accessories, Food and beverages, Health and beauty, Home and lifestyle, Sports and travel
- `Unit price`: Price of each product in $
- `Quantity`: Number of products purchased by customer
- `Tax: 5%`: tax fee for customers buying
- `Total`: Total price including tax
- `Date`: Date of purchase (Record availabl e from January 2019 to March 2019)
- `Time`: Purchase time (10 am to 9 pm)
- `Payment`: Payment used by the customer for the purchase (3 methods are available – Cash, Credit card and Ewallet)
- `COGS`: Cost of goods sold
- `Gross margin percentage`: Gross margin percentage
- `Gross income`: Gross income
- `Rating`: Customer stratification rating on their overall shopping experience (On a scale of 1 to 10)

Please analyze the data and come up with **5 insights** that make use of the following:
- **Sorting and slicing** (for example, what is the average customer rating of the top 100 highest total?)
- **Filtering** (for example, what is the average total price of sales in Mandalay City sales with a customer rating above 8?)
- **Aggregating** (for example, which product line contributes most or least to the total sales amount?)

Answer the following questions and include your final code below. When you are done, click on `Run` > `Restart Kernel and Run All Cells...` and verify the output.
- Q: What is your 1st insight? (Answer in 1-3 sentences.)
  
- A: Insight on Top 100 Sales Ratings:
     The average customer rating of the top 100 highest total sales is approximately 6.81.
     This indicates that high-value purchases do not necessarily correlate with high customer satisfaction ratings.

- Q: What is your 2nd insight? (Answer in 1-3 sentences.)
  
- A:Insight on Mandalay Sales with High Ratings:
    For sales in Mandalay with customer ratings above 8, the average total sales amount is $329.97.
  This suggests that highly satisfied customers in Mandalay tend to make higher-value purchases.
  
- Q: What is your 3rd insight? (Answer in 1-3 sentences.)
- A: Insight on Product Line Contribution:
     Among the product lines, Food and Beverages contribute the most to total sales with $56,144.84, while Health and Beauty has the lowest contribution at
     49,193.74/-
     This indicates that consumable products are more popular among customers, driving higher sales.
  
- Q: What is your 4th insight? (Answer in 1-3 sentences.)
     Insight on Payment Methods in Yangon:
- A: In Yangon, Ewallet is the most preferred payment method with 126 transactions, followed by Cash (110) and Credit Card (104).
     This shows a strong inclination towards digital payments among customers.
  
- Q: What is your 5th insight? (Answer in 1-3 sentences.)
- A:Insight on Gross Income by Customer Type:
  The average gross income for Members is $15.61, whereas for Normal customers, it is 15.15.
  This slight difference suggests that members may be making slightly more profitable purchases compared to non-members.

In [6]:
import pandas as pd
import seaborn as sns

In [7]:
SM=pd.read_csv('supermarket_sales.csv')

In [8]:
SM

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [9]:
SM.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

In [10]:
SM.describe().T

,count,mean,std,min,25%,50%,75%,max
Unit price,1000.0,55.672130,2.649463e+01,10.080000,32.875000,55.230000,77.935000,99.960000
Quantity,1000.0,5.510000,2.923431e+00,1.000000,3.000000,5.000000,8.000000,10.000000
Tax 5%,1000.0,15.379369,1.170883e+01,0.508500,5.924875,12.088000,22.445250,49.650000
Total,1000.0,322.966749,2.458853e+02,10.678500,124.422375,253.848000,471.350250,1042.650000
cogs,1000.0,307.587380,2.341765e+02,10.170000,118.497500,241.760000,448.905000,993.000000
gross margin percentage,1000.0,4.761905,6.131498e-14,4.761905,4.761905,4.761905,4.761905,4.761905
gross income,1000.0,15.379369,1.170883e+01,0.508500,5.924875,12.088000,22.445250,49.650000
Rating,1000.0,6.972700,1.718580e+00,4.000000,5.500000,7.000000,8.500000,10.000000

In [11]:
SM.isna().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

In [12]:
SM['Date']=pd.to_datetime(SM['Date'], dayfirst=False)

In [13]:
SM.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   datetime64[ns]
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(8)
memory usage: 132.9+ KB

In [14]:
SM_sort=SM.sort_values('Total',ascending=False)

In [15]:
SM_top100=SM_sort.head(100)

In [16]:
SM_top100

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
350,860-79-0874,C,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.650,1042.650,2019-02-15,14:53,Credit card,993.00,4.761905,49.650,6.6
167,687-47-8271,A,Yangon,Normal,Male,Fashion accessories,98.98,10,49.490,1039.290,2019-02-08,16:20,Credit card,989.80,4.761905,49.490,8.7
557,283-26-5248,C,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.260,1034.460,2019-01-30,20:23,Ewallet,985.20,4.761905,49.260,4.5
699,751-41-9720,C,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.750,1023.750,2019-01-12,16:18,Ewallet,975.00,4.761905,48.750,8.0
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.690,1022.490,2019-03-02,17:16,Ewallet,973.80,4.761905,48.690,4.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,435-13-4908,A,Yangon,Member,Male,Fashion accessories,86.68,8,34.672,728.112,2019-01-24,18:04,Credit card,693.44,4.761905,34.672,7.2
265,253-12-6086,A,Yangon,Member,Female,Sports and travel,98.40,7,34.440,723.240,2019-03-12,12:43,Credit card,688.80,4.761905,34.440,8.7
55,399-46-5918,C,Naypyitaw,Normal,Female,Electronic accessories,85.98,8,34.392,722.232,2019-02-28,19:01,Cash,687.84,4.761905,34.392,8.2
336,898-04-2717,A,Yangon,Normal,Male,Fashion accessories,76.40,9,34.380,721.980,2019-03-19,15:49,Ewallet,687.60,4.761905,34.380,7.5
142,338-65-2210,C,Naypyitaw,Member,Female,Health and beauty,68.60,10,34.300,720.300,2019-02-05,19:57,Cash,686.00,4.761905,34.300,9.1

In [17]:
SM_top100['Rating'].mean()

6.815000000000001

#### Average Total Price of Sales in Mandalay City with a Customer Rating Above 8

In [19]:
SM_mandalayrating=SM[(SM['City'] == 'Mandalay') & (SM['Rating'] > 8)]

In [20]:
SM_mandalayrating

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
28,145-94-9061,B,Mandalay,Normal,Female,Food and beverages,88.36,5,22.0900,463.8900,2019-01-25,19:48,Cash,441.80,4.761905,22.0900,9.6
45,132-32-9879,B,Mandalay,Member,Female,Electronic accessories,93.96,4,18.7920,394.6320,2019-03-09,18:00,Cash,375.84,4.761905,18.7920,9.5
46,370-41-7321,B,Mandalay,Member,Male,Health and beauty,56.69,9,25.5105,535.7205,2019-02-27,17:24,Credit card,510.21,4.761905,25.5105,8.4
48,669-54-1719,B,Mandalay,Member,Male,Electronic accessories,18.93,6,5.6790,119.2590,2019-02-10,12:45,Credit card,113.58,4.761905,5.6790,8.1
62,347-34-2234,B,Mandalay,Member,Female,Sports and travel,55.07,9,24.7815,520.4115,2019-02-03,13:40,Ewallet,495.63,4.761905,24.7815,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
952,574-80-1489,B,Mandalay,Member,Female,Food and beverages,62.85,4,12.5700,263.9700,2019-02-25,13:22,Ewallet,251.40,4.761905,12.5700,8.7
969,214-30-2776,B,Mandalay,Member,Female,Electronic accessories,34.49,5,8.6225,181.0725,2019-03-11,19:44,Credit card,172.45,4.761905,8.6225,9.0
970,746-04-1077,B,Mandalay,Member,Female,Food and beverages,84.63,10,42.3150,888.6150,2019-01-01,11:36,Credit card,846.30,4.761905,42.3150,9.0
985,374-38-5555,B,Mandalay,Normal,Female,Fashion accessories,63.71,5,15.9275,334.4775,2019-02-07,19:30,Ewallet,318.55,4.761905,15.9275,8.5
989,430-53-4718,B,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,2019-01-28,15:46,Credit card,602.96,4.761905,30.1480,8.4

In [21]:
SM_mandalayrating['Total'].mean()

329.9708764044944

#### Product Line Contribution to Total Sales Amount

In [23]:
product_line_sales = SM.groupby('Product line').aggregate({'Total':'sum'})

In [24]:
product_line_sales['Total'].sort_values()

Product line
Health and beauty         49193.7390
Home and lifestyle        53861.9130
Fashion accessories       54305.8950
Electronic accessories    54337.5315
Sports and travel         55122.8265
Food and beverages        56144.8440
Name: Total, dtype: float64

####  Number of Sales by Payment Method in Yangon

In [26]:
yangon_payment_methods= SM[(SM['City'] =='Yangon')]

In [27]:
yangon_payment_methods['Payment'].value_counts()

Payment
Ewallet        126
Cash           110
Credit card    104
Name: count, dtype: int64

#### Average Gross Income by Customer Type

In [29]:
SM.groupby('Customer type')['gross income'].mean()

Customer type
Member    15.609110
Normal    15.148707
Name: gross income, dtype: float64