# Exercise: Loading Data

Please load each of the 4 files containing data about numerous businesses on Yelp and answer the following questions. Include your final code below. When you are done, click on `Run` > `Restart Kernel and Run All Cells...` and verify the output.
- Q: How many rows does `yelp1.csv` contain?
- A: 627
- Q: What is the data type of `name`?
- A: Object
- Q: How many rows does `yelp2.csv` contain?
- A: 600
- Q: What is the data type of `take_out`?
- A: bool
- Q: How many rows does `yelp3.csv` contain?
- A: 629
- Q: What is the data type of `review_count`?
- A: Integer
- Q: How many rows does `yelp4.csv` contain?
- A: 638
- Q: What is the data type of `stars`?
- A: Float

## Importing data as "pandas"

In [13]:
import pandas as pd

In [15]:
Y1=pd.read_csv('yelp1.csv', sep='\t')

In [17]:
Y1

,name,main_category,sub_category,take_out,review_count,stars
0,Dairy Queen,Food,Ice Cream & Frozen Yogurt,True,10,3.5
1,Dan Cercone Hairstyling,Barbers,Beauty & Spas,False,32,4.5
2,Decio's Custom Tailoring & Formal Wear,Local Services,Sewing & Alterations,False,3,5.0
3,Dependable Brakes & Exhaust,Auto Repair,Automotive,False,4,5.0
4,Doc's Place,Bars,Pizza,True,21,3.0
...,...,...,...,...,...,...
622,Galaxy Foam & Upholstery,Local Services,Furniture Reupholstery,False,18,5.0
623,Pilot Travel Center,Automotive,Gas & Service Stations,False,18,3.5
624,Bonita Groceries,Food,Grocery,False,3,2.0
625,La Bonita Grocery Store,Food,Grocery,False,7,3.5
626,Morris Dexter OD,Optometrists,Health & Medical,False,3,3.0

In [19]:
Y1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 627 entries, 0 to 626
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           627 non-null    object
 1   main_category  627 non-null    object
 2   sub_category   627 non-null    object
 3   take_out       627 non-null    bool
 4   review_count   627 non-null    int64
 5   stars          627 non-null    float64
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 25.2+ KB

In [21]:
Y2=pd.read_csv('yelp2.csv')

In [23]:
Y2

,name,main_category,sub_category,take_out,review_count,stars
0,China Sea Chinese Restaurant,Restaurants,Chinese,True,11,2.5
1,Discount Tire Center,Tires,Automotive,False,24,4.5
2,Frankfurters,Restaurants,Hot Dogs,True,3,4.5
3,Fred Dietz Floral,Shopping,Flowers & Gifts,False,6,4.0
4,Kuhn's Market,Food,Grocery,False,8,3.5
...,...,...,...,...,...,...
595,Republic Services of Southern Nevada Recycling...,Local Services,Recycling Center,False,7,2.5
596,SA Recycling,Local Services,Recycling Center,False,3,1.5
597,Jack In the Box,Restaurants,Fast Food,True,12,3.0
598,Custom Hearth & Door,Shopping,Heating & Air Conditioning/HVAC,False,9,4.0
599,A Sunrise Towing,Automotive,Towing,False,4,1.0

In [25]:
Y2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           600 non-null    object
 1   main_category  600 non-null    object
 2   sub_category   600 non-null    object
 3   take_out       600 non-null    bool
 4   review_count   600 non-null    int64
 5   stars          600 non-null    float64
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 24.2+ KB

In [27]:
Y3=pd.read_csv('yelp3.csv',names=['name','main_category','sub_Category','take_Out','review_count','Star'])

In [29]:
Y3

,name,main_category,sub_Category,take_Out,review_count,Star
0,Miller Ace Hardware,Shopping,Hardware Stores,False,5,4.5
1,Minutello's Restaurant & Lounge,Italian,Pizza,True,8,3.0
2,Monro Muffler Brake & Service,Tires,Automotive,False,9,2.0
3,Moonlite Cafe,Restaurants,Italian,True,20,4.5
4,Morton's The Steakhouse,Restaurants,American (Traditional),True,68,4.0
...,...,...,...,...,...,...
625,Habib's Tailoring & Leather Repairs,Local Services,Sewing & Alterations,False,113,4.5
626,The UPS Store,Local Services,Shipping Centers,False,11,4.5
627,China China,Shopping,Home & Garden,False,3,5.0
628,Cigar Box,Shopping,Tobacco Shops,False,3,4.5
629,Fabric Boutique,Shopping,Arts & Crafts,False,5,4.0

In [13]:
Y3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 629 entries, 0 to 628
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Miller Ace Hardware  629 non-null    object
 1   Shopping             629 non-null    object
 2   Hardware Stores      629 non-null    object
 3   FALSE                629 non-null    bool
 4   5                    629 non-null    int64
 5   4.5                  629 non-null    float64
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 25.3+ KB

In [14]:
Y4=pd.read_csv('yelp4.csv', sep=';')

In [15]:
Y4

,name,main_category,sub_category,take_out,review_count,stars
0,Eat'n Park Restaurant,Fast Food,American (Traditional),True,21,3.5
1,Econowash Laundry,Local Services,Dry Cleaning & Laundry,False,6,2.0
2,Eddie's Pizza Haus,Italian,Pizza,True,8,4.0
3,Elite Coach Limousine,Hotels & Travel,Airport Shuttles,False,3,2.5
4,Elks B P O,Arts & Entertainment,Social Clubs,False,3,5.0
...,...,...,...,...,...,...
633,Morton's Valero Travel Plaza,Tires,Automotive,False,3,3.5
634,Cool Cuts 4 Kids,Beauty & Spas,Hair Salons,False,37,4.0
635,Great Clips,Beauty & Spas,Hair Salons,False,11,3.5
636,Silver Nugget Bowling Center,Active Life,Bowling,False,11,3.5
637,Poker Palace,Arts & Entertainment,Casinos,False,16,4.0

In [16]:
Y4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 638 entries, 0 to 637
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           638 non-null    object
 1   main_category  638 non-null    object
 2   sub_category   638 non-null    object
 3   take_out       638 non-null    bool
 4   review_count   638 non-null    int64
 5   stars          638 non-null    float64
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 25.7+ KB